# Generated by Django 4.2.7 on 2026-04-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_booking_actual_entry_booking_actual_exit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
